language: bash
services: docker

env:
  global:
    - ORGANIZATION=bscstorage
    - secure: VnxtVIsTt+jpFXQzODsQDrV34G2N8esN1CWqVMIS6mYKLX+b+S2i1BEqBN+WPq72cqBtwgA6rPyp8SGmSjtKFVkO9ScPlFNomDa569llUWF27r8Mmxzc62OAmdPHoyXsPRH0vkkVbyqh4tL+f7ruOqhkkMq+RQIOsqC0N44A9ix3kAdQefeGfcrNLkVKTeZLHcs9o/QkofIhS4odurkMJCs15OmlXAfr0YTVpfAdKNquQZIqYeoy1EMTTFT99KobsbaKgQZyjkxr7wDW2dC6aYSxJf0kgdyQX+0vObruY4S3jqdsPmCC6tp8Bl0W3DpUobq0KjFVWPskCpJHawTuGv8yGNgXuzKJQZb+FSHMY0i7i+fS9z2jUc5xfP+rCsTnikgUjJQ4doMIIyE5X3/eOwM9pIIyJIa84adzpUiZ5U9aQpp77WeSOYU03wclJRWgpOKck2aAxGD7+IhaJ4dd/BqO6XfXGLtCATAVYQ0XV4NbsDepJWgnyHSY+Yu3h3/Dk4m9Y/ybUFl6q9RdEz+XT6u27uPyUz0DqPqkCVg6DhZZEWgdJJAPKs4/UIhs/rJXfMjsNyPAwWOfvmgIxVGsSoQxbAU7JhtEhZKOu5G1fTTPWPXpBAJpVzt9sLmNj+v1j+jhe+eeHy095eEilcIFeW/ya7xfBXoPEjuEvAKjfm8=
    - secure: EcuO7T3WjqXK7QQ1DQ1HEXIxRE7ooLT64T4Q8aR98zjit3g3GofeH9H0gWQA9AChiFBQsWmL+I5E6qg0SbD7QwTmhNGUY7z5X9ltIf0Y5Tri1NvwzCpCuOmeYA5ARQ48k3osTuvYqbC+ARgJReAv3S7qov45qY20ApVRdhL9D79+wRRBRPKj1whAoAGX6JWyGHOi7wpvb0kmkhKE35zoICdXTOpFLhbBPYHi435NoYmg4aD4vlpkNkoHe1XHml6sULc/oVejfJzIdDMVVwJfGLzEyPyvqCYwODrP3omGiteEE9eN1hQ1J79u6TGI6uJ76fBWCr8lrsz1CwC3KL7BQhzi6kzgzzHCECMGdCehtisdZ6i5ALIfQwk5dgw5AVVkOcldR5lACsSEpPsYWdWWkp/Mp+kUQ7C8OdeTLcp8V+qwLOf1Gm6g6cUUjFT2du19D8z/f3/G1c8KWNzlQLD70zHMoHJoJTGurMIGV6ps0MxuJtqoWRRDavDd9gWONzdyOrWjYkbLxBZapuwTghnATA++ZHU6rFlhoxtmANKAxSuzRIKiWxRfkgkxR8ztaCxg+T5rl7IVnLvq+RP+LmKOPXPDpWAqVf8b3U2ayGO/7FpT2OsF8rACAP/27pJDpJZ6asPDy7tY0qp2pV4WUUhHh30Y9vMdS3DZzvnQQTyiyAU=
  matrix:
    - COMPILER=gcc    COMPILER_VERSION=4.8  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=4.9  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=5.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=6.5  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=7.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=8.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=gcc    COMPILER_VERSION=9.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=4.8  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=4.9  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=5.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=6.5  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=7.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=8.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=9.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - env | sort
  - cd "${COMPILER}/${COMPILER_VERSION}"
  - IMAGE="norns-build-deps:${COMPILER}${COMPILER_VERSION}-libfabric${LIBFABRIC_VERSION}-mercury${MERCURY_VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --pull --cache-from "${ORGANIZATION}/${IMAGE}" --build-arg LIBFABRIC_VERSION="v${LIBFABRIC_VERSION}" --build-arg MERCURY_VERSION="v${MERCURY_VERSION}" --tag "${IMAGE}" .
      docker run -ti --rm "$IMAGE" "$COMPILER" --version
    )

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: 
    - docker push "$ORGANIZATION"/"$IMAGE"
  on:
    branch: master
