language: bash
services: docker

env:
  global:
    - ORGANIZATION=bscstorage
    - secure: NPlsJ7kxGUDetnaiRC7DP1zDN/X00LDgKtmRz3QVQGRN2Fb6hu59c2Mlea+wbdDju6fRBdaVeCH0W52CHpuOSRSyLxY5aCotx6bc0ckWIM/vrrGTSFuYtj9vhuIqqxLc+Js0LtOwcdM4cooPFZE7FeH/KejmtjkSi4UpcsvECue/x+mEmh/ApmQaB/sCANxgrhVkT+vj/5B95MTfqglBl0+LiaV/FO5EuczpYpVBflzQv5UvEZoyjPvKAr8cuaHAVsqRiaoG2JwechNHT2FzLqIDA8riCvQi/rHEFuxYMebGWlm1UImpJFrWBpHzFRHLlTpfAE/dUxXAZXq5qZ9Jrm3UKXjQg4QigH6TVrhSiBSdCWSdEYf/YzOPYS/88zycqgcOpEsswbRyAzWf0ncb1v4N2WHFKjfvTn0/S7qstSQW7bO7SjF56VEB3KsFsbipG3WR0waVR6XXfq0jTuwjr+qKNiIxeMGCtBwm7COWO0PF/5/AsSAktAJFFCrh6vpMw/NO5cYPPWe12mhmOKoBkXCERc6M1UcH6IsSMF6/Q86C8VF6owftEJdToPVI4Kdo7dvlZPE2YdfsAb+2M0Lxi8V0ye9BwS3GvXQW4LLj0SfuMDJ93D4O1bO9uzaRVxYSjj6w8c+x4NcWFXZGvrp1xD+RkjtgbzneidHYvFJdRA8=
    - secure: KNEcmHhQ4NxhzFzsM3trxV4PQTcZrcDWU350bY/XenxnoXfLxdweWKooXlTpIrwoRVZP8V5fXmNeXBXnEfhszYn84vYhBEk4lWArA2d9av58keIOXRBasNdMYBUwL26TBzYHsYTLO349ihjfrg5+Kyru2egXX1I8ETkPECfbr3wFx47LGaKgg7aujxjRaqGIbURr+zoWVYrb29hKanz0rtUsT/e0IIAT2LSFnayipIYI5U8mISbFhXxAl8bGMELUD0iZiXHd2prMfYvnEF9POEWOLb3G1PYcBRALMcizdJqcAKMCzah3Hgjh3LwzpoHMrf6tcrg5WyonL85g16Ut9WwBNag4HgiIIaG5NX4jCP8vRgmC+T5CJmCTDWjPj1VjtuXctS2Lof6j3cautDWcKESKz+8tx4tdQH7AYXpTVYn5a4KgTOx5wXPTdt63D+09fiq+QjDgjzXKvd1D56EpTV3+khhgDlfyUzMtwWzXaozrPBtdeJNp6gtfmrfjtQaRa4WE4x6oj5ZEMQG6mYFlg9ETmZiMGMpVitUwb3RIwSkehtmGsYbSYO4tKM1GThaw6h0F6fbRdOMGIHbG9BYARxteLP6HPrNoDLrTcZpPpWoTLS1qHpuYoVRyhnnMF1aUNXLZRfvQHx5wNC3xn8k3x8MdxobxC40dxAkjuvyxPSk=
  matrix:
    - COMPILER=gcc    COMPILER_VERSION=4.8  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=4.9  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=5.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=6.5  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=7.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=8.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
    - COMPILER=gcc    COMPILER_VERSION=9.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=4.8  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=4.9  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=5.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=6.5  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=7.4  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=8.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1
      #    - COMPILER=clang  COMPILER_VERSION=9.1  LIBFABRIC_VERSION=1.7.1  MERCURY_VERSION=1.0.1

before_script:
  - env | sort
  - cd "${COMPILER}/${COMPILER_VERSION}"
  - IMAGE="norns-build-deps:${COMPILER}${COMPILER_VERSION}-libfabric${LIBFABRIC_VERSION}-mercury${MERCURY_VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --pull --cache-from "${ORGANIZATION}/${IMAGE}" --build-arg LIBFABRIC_VERSION="v${LIBFABRIC_VERSION}" --build-arg MERCURY_VERSION="v${MERCURY_VERSION}" --tag "${IMAGE}" .
      docker run -ti --rm "$IMAGE" "$COMPILER" --version
    )

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: 
    - docker push "$ORGANIZATION"/"$IMAGE"
  on:
    branch: master
